"""Extract BlockOut game tables from original/BL2.OVL into port/core/bo_tables.c."""
import os, struct, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bl2

w, uw, ds = bl2.w, bl2.uw, bl2.ds

def words(off, n): return [w(off + 2 * k) for k in range(n)]
def longs(off, n): return [struct.unpack('<i', ds(off + 4 * k, 4))[0] for k in range(n)]
def bytes_(off, n): return list(ds(off, n))
def arr(vals, per=16): return ',\n    '.join(', '.join(str(v) for v in vals[i:i + per]) for i in range(0, len(vals), per))

N_PIECES = 41
out = ['/* Generated by re/tools/gen_tables.py from original/BL2.OVL. Do not edit. */',
       '#include "bo_tables.h"', '']

# Pieces: ds:288a = {ncubes, ptr} x 41; cubes are (x,y,z) words
cubes, offs, counts = [], [], []
for p in range(N_PIECES):
    n, ptr = w(0x288a + 4 * p), uw(0x288a + 4 * p + 2)
    offs.append(len(cubes) // 3); counts.append(n)
    cubes += words(ptr, 3 * n)
out.append(f'const int8_t bo_piece_cubes[{len(cubes)}] = {{\n    {arr(cubes, 15)}\n}};')
out.append(f'const uint8_t bo_piece_ncubes[BO_NPIECES] = {{ {arr(counts, 41)} }};')
out.append(f'const uint8_t bo_piece_first[BO_NPIECES] = {{ {arr(offs, 41)} }};')

# Block sets: ds:2968 = {count, ptr to byte list} x 3
sets = []
for s in range(3):
    n, ptr = w(0x2968 + 4 * s), uw(0x2968 + 4 * s + 2)
    sets.append(bytes_(ptr, n))
out.append('const uint8_t bo_set_count[3] = { %s };' % ', '.join(str(len(s)) for s in sets))
out.append('const uint8_t bo_set_list[3][BO_NPIECES] = {\n    %s\n};' % ',\n    '.join('{ ' + ', '.join(map(str, s)) + ' }' for s in sets))

# Rotations: ds:29c2 = 6 x 3 x {axis, sign, pos}
rot = words(0x29c2, 6 * 9)
out.append('const bo_pose bo_rotations[6] = {\n    %s\n};' % ',\n    '.join(
    '{{ ' + ', '.join('{%d, %d, %d}' % tuple(rot[r * 9 + 3 * i: r * 9 + 3 * i + 3]) for i in range(3)) + ' }}' for r in range(6)))

nlev = w(0x0f4c)
assert nlev == 11
out.append(f'const int16_t bo_fall_delay[BO_NLEVELS] = {{ {arr(words(0x0f4e, nlev))} }};')
out.append(f'const int16_t bo_rot_steps[2][3] = {{ {{ {arr(words(0x117c, 3))} }}, {{ {arr(words(0x1182, 3))} }} }};')
out.append(f'const int16_t bo_move_steps[2][3] = {{ {{ {arr(words(0x1188, 3))} }}, {{ {arr(words(0x118e, 3))} }} }};')
out.append(f'const int32_t bo_set_factor[3] = {{ {arr(longs(0x2b04, 3))} }};')
out.append(f'const int16_t bo_depth_factor[BO_MAX_DEP + 1] = {{ {arr(words(0x2b56, 19), 19)} }};')
out.append(f'const int16_t bo_piece_class[BO_NPIECES] = {{ {arr(words(0x2b10, 41), 41)} }};')
out.append(f'const int32_t bo_class_factor[10] = {{ {arr(longs(0x2b7c, 10))} }};')
out.append(f'const int16_t bo_pit_max[3] = {{ {arr(words(0x0e24, 3))} }};')
out.append(f'const int16_t bo_pit_min[3] = {{ {arr(words(0x0e2a, 3))} }};')
pre = [words(0x0d64 + 8 * k, 4) for k in range(3)]
out.append('const int16_t bo_presets[3][4] = {\n    %s\n};' % ',\n    '.join('{ ' + ', '.join(map(str, p)) + ' }' for p in pre))
out.append(f'const int16_t bo_default_setup[6] = {{ {arr(words(0x0d8f, 6))} }};')

dst = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'port', 'core', 'bo_tables.c')
open(dst, 'w').write('\n'.join(out) + '\n')
print('wrote', os.path.normpath(dst))
